apiVersion: v1
kind: Service
metadata:
  name: llm-connection
  name: ollama-chat-app-service
spec:
  selector:
    app: ollama-chat-app
  ports:
  - protocol: TCP
    port: 80 # External port you want to expose
    targetPort: 7860 # Container port
  type: LoadBalancer # Or NodePort, ClusterIP depending on how you want to expose it